# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_afc_report_action = QtGui.QAction(MainWindow)
        self.open_afc_report_action.setObjectName("open_afc_report_action")
        self.exit_action = QtGui.QAction(MainWindow)
        self.exit_action.setObjectName("exit_action")
        self.settings_action = QtGui.QAction(MainWindow)
        self.settings_action.setObjectName("settings_action")
        self.menu.addAction(self.open_afc_report_action)
        self.menu.addAction(self.settings_action)
        self.menu.addSeparator()
        self.menu.addAction(self.exit_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калибровка вибростенда"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.open_afc_report_action.setText(_translate("MainWindow", "Открыть протокол АЧХ..."))
        self.open_afc_report_action.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.exit_action.setText(_translate("MainWindow", "Выход"))
        self.settings_action.setText(_translate("MainWindow", "Настройки..."))
        self.settings_action.setShortcut(_translate("MainWindow", "Ctrl+P"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
